<?php

namespace Amora\Core\Value;

use Amora\Core\Core;

final class Country
{
    public static array $countries = [
        ['id' => 'AT', 'name' => 'Austria'],
        ['id' => 'BE', 'name' => 'Belgium'],
        ['id' => 'BG', 'name' => 'Bulgaria'],
        ['id' => 'HR', 'name' => 'Croatia'],
        ['id' => 'CY', 'name' => 'Cyprus'],
        ['id' => 'CZ', 'name' => 'Czech Republic'],
        ['id' => 'DK', 'name' => 'Denmark'],
        ['id' => 'EE', 'name' => 'Estonia'],
        ['id' => 'FI', 'name' => 'Finland'],
        ['id' => 'FR', 'name' => 'France'],
        ['id' => 'DE', 'name' => 'Germany'],
        ['id' => 'GR', 'name' => 'Greece'],
        ['id' => 'HU', 'name' => 'Hungary'],
        ['id' => 'IE', 'name' => 'Ireland'],
        ['id' => 'IT', 'name' => 'Italy'],
        ['id' => 'LV', 'name' => 'Latvia'],
        ['id' => 'LT', 'name' => 'Lithuania'],
        ['id' => 'LU', 'name' => 'Luxembourg'],
        ['id' => 'MT', 'name' => 'Malta'],
        ['id' => 'NL', 'name' => 'Netherlands'],
        ['id' => 'PL', 'name' => 'Poland'],
        ['id' => 'PT', 'name' => 'Portugal'],
        ['id' => 'RO', 'name' => 'Romania'],
        ['id' => 'SK', 'name' => 'Slovakia'],
        ['id' => 'SI', 'name' => 'Slovenia'],
        ['id' => 'ES', 'name' => 'Spain'],
        ['id' => 'SE', 'name' => 'Sweden'],
        ['id' => 'GB', 'name' => 'United Kingdom'],

        ['id' => 'AX', 'name' => 'Aland Islands'],
        ['id' => 'AF', 'name' => 'Afghanistan'],
        ['id' => 'AL', 'name' => 'Albania'],
        ['id' => 'DZ', 'name' => 'Algeria'],
        ['id' => 'AS', 'name' => 'American Samoa'],
        ['id' => 'AD', 'name' => 'Andorra'],
        ['id' => 'AO', 'name' => 'Angola'],
        ['id' => 'AI', 'name' => 'Anguilla'],
        ['id' => 'AG', 'name' => 'Antigua and Barbuda'],
        ['id' => 'AR', 'name' => 'Argentina'],
        ['id' => 'AM', 'name' => 'Armenia'],
        ['id' => 'AW', 'name' => 'Aruba'],
        ['id' => 'AU', 'name' => 'Australia'],
        ['id' => 'AZ', 'name' => 'Azerbaijan'],
        ['id' => 'BS', 'name' => 'Bahamas'],
        ['id' => 'BH', 'name' => 'Bahrain'],
        ['id' => 'BD', 'name' => 'Bangladesh'],
        ['id' => 'BB', 'name' => 'Barbados'],
        ['id' => 'BY', 'name' => 'Belarus'],
        ['id' => 'BZ', 'name' => 'Belize'],
        ['id' => 'BJ', 'name' => 'Benin'],
        ['id' => 'BM', 'name' => 'Bermuda'],
        ['id' => 'BT', 'name' => 'Bhutan'],
        ['id' => 'BO', 'name' => 'Bolivia'],
        ['id' => 'BA', 'name' => 'Bosnia and Herzegovina'],
        ['id' => 'BW', 'name' => 'Botswana'],
        ['id' => 'BR', 'name' => 'Brazil'],
        ['id' => 'VG', 'name' => 'British Virgin Islands'],
        ['id' => 'BN', 'name' => 'Brunei Darussalam'],
        ['id' => 'BF', 'name' => 'Burkina Faso'],
        ['id' => 'BI', 'name' => 'Burundi'],
        ['id' => 'KH', 'name' => 'Cambodia'],
        ['id' => 'CM', 'name' => 'Cameroon'],
        ['id' => 'CA', 'name' => 'Canada'],
        ['id' => 'CV', 'name' => 'Cape Verde'],
        ['id' => 'CW', 'name' => 'Curacao'],
        ['id' => 'KY', 'name' => 'Cayman Islands'],
        ['id' => 'CF', 'name' => 'Central African Republic'],
        ['id' => 'TD', 'name' => 'Chad'],
        ['id' => 'CL', 'name' => 'Chile'],
        ['id' => 'CN', 'name' => 'China'],
        ['id' => 'CX', 'name' => 'Christmas Island'],
        ['id' => 'CO', 'name' => 'Colombia'],
        ['id' => 'KM', 'name' => 'Comoros'],
        ['id' => 'CG', 'name' => 'Congo'],
        ['id' => 'CD', 'name' => 'Congo, The Democratic Republic of The'],
        ['id' => 'CK', 'name' => 'Cook Islands'],
        ['id' => 'CR', 'name' => 'Costa Rica'],
        ['id' => 'CU', 'name' => 'Cuba'],
        ['id' => 'DJ', 'name' => 'Djibouti'],
        ['id' => 'DM', 'name' => 'Dominica'],
        ['id' => 'DO', 'name' => 'Dominican Republic'],
        ['id' => 'EC', 'name' => 'Ecuador'],
        ['id' => 'EG', 'name' => 'Egypt'],
        ['id' => 'SV', 'name' => 'El Salvador'],
        ['id' => 'GQ', 'name' => 'Equatorial Guinea'],
        ['id' => 'ER', 'name' => 'Eritrea'],
        ['id' => 'ET', 'name' => 'Ethiopia'],
        ['id' => 'FO', 'name' => 'Faroe Islands'],
        ['id' => 'FJ', 'name' => 'Fiji'],
        ['id' => 'GF', 'name' => 'French Guiana'],
        ['id' => 'PF', 'name' => 'French Polynesia'],
        ['id' => 'TF', 'name' => 'French Southern Territories'],
        ['id' => 'GA', 'name' => 'Gabon'],
        ['id' => 'GM', 'name' => 'Gambia'],
        ['id' => 'GE', 'name' => 'Georgia'],
        ['id' => 'GH', 'name' => 'Ghana'],
        ['id' => 'GI', 'name' => 'Gibraltar'],
        ['id' => 'GL', 'name' => 'Greenland'],
        ['id' => 'GD', 'name' => 'Grenada'],
        ['id' => 'GP', 'name' => 'Guadeloupe'],
        ['id' => 'GU', 'name' => 'Guam'],
        ['id' => 'GT', 'name' => 'Guatemala'],
        ['id' => 'GG', 'name' => 'Guernsey'],
        ['id' => 'GN', 'name' => 'Guinea'],
        ['id' => 'GY', 'name' => 'Guyana'],
        ['id' => 'HT', 'name' => 'Haiti'],
        ['id' => 'HN', 'name' => 'Honduras'],
        ['id' => 'HK', 'name' => 'Hong Kong'],
        ['id' => 'ID', 'name' => 'Indonesia'],
        ['id' => 'IS', 'name' => 'Iceland'],
        ['id' => 'IN', 'name' => 'India'],
        ['id' => 'IR', 'name' => 'Iran, Islamic Republic of'],
        ['id' => 'IQ', 'name' => 'Iraq'],
        ['id' => 'IM', 'name' => 'Isle of Man'],
        ['id' => 'IL', 'name' => 'Israel'],
        ['id' => 'CI', 'name' => 'Ivory Coast'],
        ['id' => 'JM', 'name' => 'Jamaica'],
        ['id' => 'JP', 'name' => 'Japan'],
        ['id' => 'JE', 'name' => 'Jersey'],
        ['id' => 'JO', 'name' => 'Jordan'],
        ['id' => 'KZ', 'name' => 'Kazakhstan'],
        ['id' => 'KE', 'name' => 'Kenya'],
        ['id' => 'KI', 'name' => 'Kiribati'],
        ['id' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of'],
        ['id' => 'KR', 'name' => 'Korea, Republic of'],
        ['id' => 'KW', 'name' => 'Kuwait'],
        ['id' => 'KG', 'name' => 'Kyrgyzstan'],
        ['id' => 'LB', 'name' => 'Lebanon'],
        ['id' => 'LS', 'name' => 'Lesotho'],
        ['id' => 'LR', 'name' => 'Liberia'],
        ['id' => 'LY', 'name' => 'Libyan Arab Jamahiriya'],
        ['id' => 'LI', 'name' => 'Liechtenstein'],
        ['id' => 'MO', 'name' => 'Macao'],
        ['id' => 'MK', 'name' => 'Macedonia'],
        ['id' => 'MG', 'name' => 'Madagascar'],
        ['id' => 'MW', 'name' => 'Malawi'],
        ['id' => 'MY', 'name' => 'Malaysia'],
        ['id' => 'MV', 'name' => 'Maldives'],
        ['id' => 'ML', 'name' => 'Mali'],
        ['id' => 'MH', 'name' => 'Marshall Islands'],
        ['id' => 'MQ', 'name' => 'Martinique'],
        ['id' => 'MR', 'name' => 'Mauritania'],
        ['id' => 'MU', 'name' => 'Mauritius'],
        ['id' => 'YT', 'name' => 'Mayotte'],
        ['id' => 'MX', 'name' => 'Mexico'],
        ['id' => 'FM', 'name' => 'Micronesia, Federated States of'],
        ['id' => 'MD', 'name' => 'Moldova, Republic of'],
        ['id' => 'MC', 'name' => 'Monaco'],
        ['id' => 'MN', 'name' => 'Mongolia'],
        ['id' => 'ME', 'name' => 'Montenegro'],
        ['id' => 'MF', 'name' => 'Collectivity of Saint Martin'],
        ['id' => 'MS', 'name' => 'Montserrat'],
        ['id' => 'MA', 'name' => 'Morocco'],
        ['id' => 'MZ', 'name' => 'Mozambique'],
        ['id' => 'MM', 'name' => 'Myanmar'],
        ['id' => 'NA', 'name' => 'Namibia'],
        ['id' => 'NR', 'name' => 'Nauru'],
        ['id' => 'NP', 'name' => 'Nepal'],
        ['id' => 'AN', 'name' => 'Netherlands Antilles'],
        ['id' => 'NC', 'name' => 'New Caledonia'],
        ['id' => 'NZ', 'name' => 'New Zealand'],
        ['id' => 'NI', 'name' => 'Nicaragua'],
        ['id' => 'NE', 'name' => 'Niger'],
        ['id' => 'NG', 'name' => 'Nigeria'],
        ['id' => 'NU', 'name' => 'Niue'],
        ['id' => 'NF', 'name' => 'Norfolk Island'],
        ['id' => 'MP', 'name' => 'Northern Mariana Islands'],
        ['id' => 'NO', 'name' => 'Norway'],
        ['id' => 'OM', 'name' => 'Oman'],
        ['id' => 'PK', 'name' => 'Pakistan'],
        ['id' => 'PW', 'name' => 'Palau'],
        ['id' => 'PS', 'name' => 'Palestine'],
        ['id' => 'PA', 'name' => 'Panama'],
        ['id' => 'PG', 'name' => 'Papua New Guinea'],
        ['id' => 'PY', 'name' => 'Paraguay'],
        ['id' => 'PE', 'name' => 'Peru'],
        ['id' => 'PH', 'name' => 'Philippines'],
        ['id' => 'PN', 'name' => 'Pitcairn'],
        ['id' => 'PR', 'name' => 'Puerto Rico'],
        ['id' => 'QA', 'name' => 'Qatar'],
        ['id' => 'RE', 'name' => 'Réunion'],
        ['id' => 'RU', 'name' => 'Russia'],
        ['id' => 'RW', 'name' => 'Rwanda'],
        ['id' => 'SH', 'name' => 'Saint Helena'],
        ['id' => 'KN', 'name' => 'Saint Kitts and Nevis'],
        ['id' => 'LC', 'name' => 'Saint Lucia'],
        ['id' => 'PM', 'name' => 'Saint Pierre and Miquelon'],
        ['id' => 'VC', 'name' => 'Saint Vincent and The Grenadines'],
        ['id' => 'WS', 'name' => 'Samoa'],
        ['id' => 'SM', 'name' => 'San Marino'],
        ['id' => 'ST', 'name' => 'Sao Tome and Principe'],
        ['id' => 'SA', 'name' => 'Saudi Arabia'],
        ['id' => 'SN', 'name' => 'Senegal'],
        ['id' => 'RS', 'name' => 'Serbia'],
        ['id' => 'SC', 'name' => 'Seychelles'],
        ['id' => 'SL', 'name' => 'Sierra Leone'],
        ['id' => 'SG', 'name' => 'Singapore'],
        ['id' => 'SB', 'name' => 'Solomon Islands'],
        ['id' => 'SO', 'name' => 'Somalia'],
        ['id' => 'ZA', 'name' => 'South Africa'],
        ['id' => 'LK', 'name' => 'Sri Lanka'],
        ['id' => 'SD', 'name' => 'Sudan'],
        ['id' => 'SR', 'name' => 'Suriname'],
        ['id' => 'SJ', 'name' => 'Svalbard and Jan Mayen'],
        ['id' => 'SZ', 'name' => 'Swaziland'],
        ['id' => 'CH', 'name' => 'Switzerland'],
        ['id' => 'SY', 'name' => 'Syrian Arab Republic'],
        ['id' => 'TW', 'name' => 'Taiwan, Province of China'],
        ['id' => 'TJ', 'name' => 'Tajikistan'],
        ['id' => 'TZ', 'name' => 'Tanzania, United Republic of'],
        ['id' => 'TH', 'name' => 'Thailand'],
        ['id' => 'TG', 'name' => 'Togo'],
        ['id' => 'TK', 'name' => 'Tokelau'],
        ['id' => 'TO', 'name' => 'Tonga'],
        ['id' => 'TT', 'name' => 'Trinidad and Tobago'],
        ['id' => 'TN', 'name' => 'Tunisia'],
        ['id' => 'TR', 'name' => 'Turkey'],
        ['id' => 'TM', 'name' => 'Turkmenistan'],
        ['id' => 'TC', 'name' => 'Turks and Caicos Islands'],
        ['id' => 'TV', 'name' => 'Tuvalu'],
        ['id' => 'UG', 'name' => 'Uganda'],
        ['id' => 'UA', 'name' => 'Ukraine'],
        ['id' => 'AE', 'name' => 'United Arab Emirates'],
        ['id' => 'US', 'name' => 'United States'],
        ['id' => 'UM', 'name' => 'United States Minor Outlying Islands'],
        ['id' => 'UY', 'name' => 'Uruguay'],
        ['id' => 'UZ', 'name' => 'Uzbekistan'],
        ['id' => 'VU', 'name' => 'Vanuatu'],
        ['id' => 'VA', 'name' => 'Vatican City'],
        ['id' => 'VE', 'name' => 'Venezuela'],
        ['id' => 'VN', 'name' => 'Viet Nam'],
        ['id' => 'WF', 'name' => 'Wallis and Futuna'],
        ['id' => 'EH', 'name' => 'Western Sahara'],
        ['id' => 'YE', 'name' => 'Yemen'],
        ['id' => 'ZM', 'name' => 'Zambia'],
        ['id' => 'ZW', 'name' => 'Zimbabwe']
    ];

    public static function getCountryNameFromCountryIsoCode(string $countryIsoCode): string
    {
        if (empty($countryIsoCode) || strlen($countryIsoCode) !== 2) {
            Core::getDefaultLogger()->logError('Country ISO code not valid: ' . $countryIsoCode);
            return '';
        }

        foreach (self::$countries as $key => $country) {
            if ($country['id'] === $countryIsoCode) {
                return self::$countries[$key]['name'];
            }
        }

        Core::getDefaultLogger()->logError('Country code not found: ' . $countryIsoCode);
        return '';
    }
}

