<?php

use uve\core\module\user\service\UserService;

return [
    'siteName' => 'Victor Gonzalez',
    'siteTitle' => '',
    'siteDescription' => 'Soy un programador web.',

    'navDashboard' => 'Escritorio',
    'navCustomiseInvitation' => 'Personalizar invitación',
    'navGuests' => 'Invitados',
    'navAccount' => 'Tus datos',
    'navEventDetails' => 'Datos de la boda',
    'navSignOut' => 'Salir',
    'navSignIn' => 'Entra',
    'navSignUp' => 'Regístrate',
    'navChangePassword' => 'Cambiar contraseña',
    'navDownloadAccountData' => 'Descargar tus datos',
    'navDeleteAccount' => 'Eliminar cuenta',
    'navAdminDashboard' => 'Dashboard',
    'navAdminUsers' => 'Usuarios',
    'navAdminImages' => 'Imágenes',
    'navAdminArticles' => 'Artículos',
    'navAdminEvents' => 'Eventos',

    'authenticationActionHomeLink' => 'Volver a la página de entrada',
    'authenticationLoginSubtitle' => '¡Bienvenido/a de nuevo, adelante!',
    'authenticationLoginFirstTimeBefore' => '¿Tu primera vez en',
    'authenticationRegisterSubtitle' => 'A un paso de tus invitaciones de boda.',
    'authenticationRegisterTOS' => 'Al registrarte aceptas los <a href="#">términos de uso</a> y la <a href="#">política de privacidad</a>.',
    'authenticationRegisterPasswordHelp' => 'Longitud mínima: ' . UserService::USER_PASSWORD_MIN_LENGTH . ' caracteres. Recomenable: letras, números y símbolos.',
    'authenticationRegisterAlreadyLogin' => '¿Ya tienes una cuenta?',

    'authenticationForgotPassword' => '¿Olvidaste tu contraseña?',
    'authenticationForgotPasswordSubtitle' => 'No te preocupes, introduce el correo electrónico que utilizaste para registrarte y te enviaremos un enlace para restaurar tu contraseña.',
    'authenticationForgotPasswordAction' => 'Enviar enlace de restauración',
    'authenticationForgotPasswordActionSuccess' => 'Correo enviado. Comprueba la bandeja de entrada de tu correo electrónico (<b><span id="register-feedback-email"></span></b>) y sigue las instruciones.',

    'authenticationPasswordResetSubtitle' => 'Cambia tu contraseña',
    'authenticationPasswordResetActionSuccess' => 'Se ha cambiado la contraseña correctamente.',
    'authenticationPasswordResetAlreadyLogin' => '¿Quieres <a href="%s/login">entrar en tu cuenta</a> sin cambiar tu contraseña?',

    'authenticationInviteRequest' => 'Consigue una invitación',
    'authenticationInviteRequestSubtitle' => 'La web está actualmente en beta privada, estamos trajando para asegurarnos de que todo funciona correctamente. Tenemos muchas ganas de que esté lista para que la puedas utilizar. Déjanos tu correo y te enviaremos una invitación tan pronto como sea posible. Solo utilizaremos tu correo para enviarte la invitación. <br>¡Gracias por tu paciencia!',
    'authenticationInviteRequestActionSuccess' => '<h2>Petición recibida correctamente</h2><p>Tu correo: <b><span id="register-feedback-email"></span></b>.</p><p>¡Gracias!</p>',
    'authenticationInviteRequestHomeLink' => 'Volver a la página principal',
    'authenticationInviteRequestFormAction' => 'Pedir una invitación',

    'formPlaceholderUserName' => 'Tu nombre',
    'formPlaceholderEmail' => 'Tu correo electrónico',
    'formPlaceholderPassword' => 'Tu contraseña',
    'formPlaceholderCreatePassword' => 'Crea una contraseña',
    'formPlaceholderPasswordNew' => 'Nueva contraseña',
    'formPlaceholderPasswordConfirmation' => 'Repite la contraseña',
    'formLoginAction' => 'Entrar',
    'formPasswordResetAction' => 'Cambiar contraseña',
    'formGuestTitle' => 'Añadir',
    'formGuestName' => 'Nombre del invitado/a',
    'formGuestNamePlaceholder' => 'Nombre',
    'formGuestNameHelp' => 'Visible también para el/la invitado/a.',
    'formGuestEmail' => 'Correo electrónico',
    'formGuestEmailPlaceholder' => 'nombre@ejemplo.com',
    'formGuestPhone' => 'Teléfono',
    'formGuestPhonePlaceholder' => '+34 611 222 333',
    'formGuestEmailFrom' => 'De',
    'formGuestEmailTo' => 'Para',
    'formGuestEmailSendAction' => 'Enviar',
    'formGuestEmailSubject' => 'Asunto',
    'formGuestEmailContent' => 'Contenido',
    'formGuestSaveAction' => 'Guardar',
    'formGuestDeleteAction' => 'Eliminar',
    'formGuestCancelAction' => 'Cancelar',
    'formGuestModifyAction' => 'Modificar',

    'dashboardGuests' => 'Invitados/as',
    'dashboardTotalGuests' => 'Total invitados',
    'dashboardGuestTableTable' => 'Invitaciones por estado',
    'dashboardGoTo' => 'Ir a...',
    'dashboardManageGuests' => 'Gestionar lista de invitados y/o enviar invitaciones',
    'dashboardManageWeddingDetails' => 'Cambiar datos de la boda',
    'dashboardAnd' => 'y',

    'tableTitleName' => 'Nombre',
    'tableTitleRsvp' => 'Invitación',
    'tableInfoPreview' => 'Previsualizar invitación',
    'tableInfoSendByEmail' => 'Enviar por correo electrónico',
    'tableInfoSendByWhatsApp' => 'Enviar por WhatsApp',

    'invitationSendByEmailTitle' => 'Enviar invitación por correo electrónico',
    'invitationPreviewCloseAction' => 'Estás previsualizando la invitación. <span>Click aquí para cerrar.</span>',

    'invitationRsvpYes' => 'Confirmadas',
    'invitationRsvpYesDescription' => 'Asistencia confirmada',
    'invitationRsvpNo' => 'Declinadas',
    'invitationRsvpNoDescription' => 'Asistencia declinada',
    'invitationViewed' => 'Abiertas',
    'invitationViewedDescription' => 'Las invitaciones han sido enviadas y vistas pero no han sido respondidas',
    'invitationSent' => 'Enviadas',
    'invitationSentDescription' => 'Las invitaciones han sido enviadas pero no han sido abiertas por lo que tampoco han sido respondidas',
    'invitationNotSent' => 'No enviadas',
    'invitationNotSentDescription' => 'Las invitaciones no han sido enviadas',

    'globalRequired' => 'Obligatorio'
];
