<?php

use uve\core\module\user\service\UserService;

return [
    'siteName' => 'CONVIDADES',
    'siteTitle' => 'Invitacións de voda dixitais',
    'siteDescription' => 'Crea e personaliza as túas invitacións de voda no móbil ou ordenador. Envíaas por WhatsApp ou correo electrónico. Recibe confirmacións de asistencia.',

    'navDashboard' => 'Escritorio',
    'navCustomiseInvitation' => 'Personalizar invitación',
    'navGuests' => 'Convidados',
    'navAccount' => 'Os teus datos',
    'navEventDetails' => 'Datos da voda',
    'navSignOut' => 'Saír',
    'navSignIn' => 'Entra',
    'navSignUp' => 'Rexístrate',
    'navChangePassword' => 'Cambiar contrasinal',
    'navDownloadAccountData' => 'Descargar os teus datos',
    'navDeleteAccount' => 'Eliminar conta',
    'navAdminDashboard' => 'Dashboard',
    'navAdminUsers' => 'Usuarios',
    'navAdminArticles' => 'Artigos',
    'navAdminEvents' => 'Eventos',

    'authenticationActionHomeLink' => 'Volver á páxina de entrada',
    'authenticationLoginSubtitle' => 'Benvida/o de volta. Adiante!',
    'authenticationLoginFirstTimeBefore' => 'A túa primeira vez en',
    'authenticationRegisterSubtitle' => 'A un paso das túas invitacións de voda.',
    'authenticationRegisterTOS' => 'Ao rexistráreste aceptas os <a href="#">termos de uso</a> e a <a href="#">política de privacidade</a>.',
    'authenticationRegisterPasswordHelp' => 'Lonxitude mínima: ' . UserService::USER_PASSWORD_MIN_LENGTH . ' caracteres. Recomenable: letras, números e símbolos.',
    'authenticationRegisterAlreadyLogin' => 'Xa tes unha conta?',

    'authenticationForgotPassword' => 'Esquecíches o teu contrasinal?',
    'authenticationForgotPasswordSubtitle' => 'Non te preocupes, introduce o correo electrónico co que te rexistraches e enviarémosche unha ligazón para restaurar o teu contrasinal.',
    'authenticationForgotPasswordAction' => 'Enviar ligazón de restauración',
    'authenticationForgotPasswordActionSuccess' => 'Correo enviado. Comproba a bandexa de entrada do teu correo electrónico (<b><span id="register-feedback-email"></span></b>) e segue as instruccións.',

    'authenticationPasswordResetSubtitle' => 'Cambia o contrasinal',
    'authenticationPasswordResetActionSuccess' => 'Cambiouse o contrasinal correctamente.',
    'authenticationPasswordResetAlreadyLogin' => 'Queres <a href="%s/login">entrar na túa conta</a> sen cambiar o contrasinal?',

    'formPlaceholderUserName' => 'O teu nome',
    'formPlaceholderEmail' => 'O teu correo electrónico',
    'formPlaceholderPassword' => 'O teu contrasinal',
    'formPlaceholderCreatePassword' => 'Crea un contrasinal',
    'formPlaceholderPasswordNew' => 'Novo contrasinal',
    'formPlaceholderPasswordConfirmation' => 'Repite o contrasinal',
    'formLoginAction' => 'Entrar',
    'formPasswordResetAction' => 'Cambiar contrasinal',
    'formGuestTitle' => 'Engadir',
    'formGuestName' => 'Nome do convidado/a',
    'formGuestNamePlaceholder' => 'Nome',
    'formGuestNameHelp' => 'Visible tamén para o convidado/a.',
    'formGuestEmail' => 'Correo electrónico',
    'formGuestEmailPlaceholder' => 'nome@exemplo.com',
    'formGuestPhone' => 'Teléfono',
    'formGuestPhonePlaceholder' => '+34 611 222 333',
    'formGuestEmailFrom' => 'De',
    'formGuestEmailTo' => 'Para',
    'formGuestEmailSendAction' => 'Enviar',
    'formGuestEmailSubject' => 'Asunto',
    'formGuestEmailContent' => 'Contido',
    'formGuestSaveAction' => 'Gardar',
    'formGuestDeleteAction' => 'Eliminar',
    'formGuestCancelAction' => 'Cancelar',
    'formGuestModifyAction' => 'Modificar',

    'dashboardGuests' => 'Convidados/as',
    'dashboardTotalGuests' => 'Total convidados',
    'dashboardGuestTableTable' => 'Invitacións agrupadas por estado',
    'dashboardGoTo' => 'Ir a...',
    'dashboardManageGuests' => 'Xestionar lista de convidados/as e/ou enviar envitacións',
    'dashboardManageWeddingDetails' => 'Cambiar datos da voda',
    'dashboardAnd' => 'e',

    'tableTitleName' => 'Nome',
    'tableTitleRsvp' => 'Invitación',
    'tableInfoPreview' => 'Previsualizar invitación',
    'tableInfoSendByEmail' => 'Enviar por correo electrónico',
    'tableInfoSendByWhatsApp' => 'Enviar por WhatsApp',

    'invitationSendByEmailTitle' => 'Enviar invitación por correo electrónico',
    'invitationPreviewCloseAction' => 'Estás previsualizando a invitación. <span>Clic aquí para pechar.</span>',
    'invitationRsvpYes' => 'Confirmadas',
    'invitationRsvpYesDescription' => 'A/O convidado/a confirmou a súa asistencia',
    'invitationRsvpNo' => 'Declinadas',
    'invitationRsvpNoDescription' => 'A/O convidado declinou a súa asitencia',
    'invitationViewed' => 'Abertas',
    'invitationViewedDescription' => 'As invitacións foron enviadas e abertas polo convidado/a pero aínda non obtiveron resposta',
    'invitationSent' => 'Enviadas',
    'invitationSentDescription' => 'As invitacións foron enviadas pero aínda non foron abertas polo que tampouco obtiveron resposta',
    'invitationNotSent' => 'Non enviadas',
    'invitationNotSentDescription' => 'As invitacións aínda non foron enviadas',

    'globalRequired' => 'Obrigatorio',
];
