<?php

namespace Amora\Core\Module\Analytics\Value;

class BotUserAgent
{
    public static array $agents = [
        'bingbot' => true,
        'WhatsApp' => true,
        'Googlebot' => true,
        'facebookexternalhit' => true,
        'Applebot' => true,
        'DuckDuckGo' => true,
        'YandexBot' => true,
        'Java' => true,
        'Go-http-client' => true,
        'Go' => true,
        'Expanse' => true,
        'Dalvik' => true,
        'WordPress' => true,
        'got' => true,
        'DuckDuckBot-Https' => true,
        'Test' => true,
        'facebook-processing' => true,
        'GuzzleHttp' => true,
        'ALittle' => true,
        'cortex' => true,
        'IABot' => true,
        'IonCrawl' => true,
        'Validator' => true,
        'RepoLookoutBot' => true,
        'WebCopier' => true,
        'BUbiNG' => true,
        'httpx' => true,
        'W3C' => true,
        'Twitterbot' => true,
        'Googlebot-Image' => true,
        'OnalyticaBot' => true,
        'Pandalytics' => true,
        'Python' => true,
        'Python-httplib2' => true,
        'python-urllib3' => true,
        'python-requests' => true,
        'Python-urllib' => true,
        'webprosbot' => true,
        'Keybot' => true,
        'panscient' => true,
        'NetSystemsResearch' => true,
        'Baiduspider' => true,
        'curl' => true,
        'UC Browser' => true,
        'serpstatbot' => true,
        'Apache-HttpClient' => true,
        'netEstate' => true,
        'GRequests' => true,
        'okhttp' => true,
        'url' => true,
        'libwww-perl' => true,
        'https' => true,
        'pantest' => true,
        'ff' => true,
        'colly' => true,
        'APIs-Google' => true,
        'Xenu' => true,
        'AppleWebKit' => true,
        'node-fetch' => true,
        'CheckMarkNetwork' => true,
        'CATExplorador' => true,
        'UCWEB' => true,
        'ZaldamoSearchBot' => true,
        'Embarcadero' => true,
        '2ip' => true,
        'Screaming' => true,
        'l9tcpid' => true,
        'Report' => true,
        'AnyConnect' => true,
        'be' => true,
        'Cisco' => true,
        'lkxscan' => true,
        'Internet-structure-research-project-bot' => true,
        'ZaldomoSearchBot' => true,
        'xxx' => true,
        'Cpanel-HTTP-Client' => true,
        'DraGunov' => true,
        'Fuzz' => true,
        'go-resty' => true,
        'req' => true,
        'PolycomRealPresenceTrio-Trio' => true,
        'SafeDNSBot' => true,
        'RestSharp' => true,
    ];

    public static function isBot(string $item): bool
    {
        if (empty($item)) {
            return false;
        }

        return self::$agents[$item] ?? false;
    }
}
